"""Add parent_id for versioning

Revision ID: 359b6d186e4d
Revises: f57d8abd96a2
Create Date: 2026-06-20 03:33:13.306720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359b6d186e4d'
down_revision: Union[str, Sequence[str], None] = 'f57d8abd96a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_apis', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'generated_apis', 'generated_apis', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_apis', type_='foreignkey')
    op.drop_column('generated_apis', 'parent_id')
    # ### end Alembic commands ###
