"""Add is _deleted column

Revision ID: f43e30d8cb15
Revises: 359b6d186e4d
Create Date: 2026-07-02 00:25:30.726645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43e30d8cb15'
down_revision: Union[str, Sequence[str], None] = '359b6d186e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_apis', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_apis', 'is_deleted')
    # ### end Alembic commands ###
