"""Add generated_apis table

Revision ID: f57d8abd96a2
Revises: a1640a0430cf
Create Date: 2026-06-17 07:18:00.569775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57d8abd96a2'
down_revision: Union[str, Sequence[str], None] = 'a1640a0430cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_apis', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_apis', 'created_at')
    # ### end Alembic commands ###
